"""add foreign key from user to wallet

Revision ID: 5e665e19a884
Revises: f71e8fa7ed6f
Create Date: 2021-10-29 00:51:48.874524

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5e665e19a884'
down_revision = 'f71e8fa7ed6f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('wallet', sa.Column('user_id', sa.Integer(), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('wallet', 'user_id')
    # ### end Alembic commands ###
