"""removes relation product-order one-to-many

Revision ID: 61507cbdfbb6
Revises: 67144dfbc5dd
Create Date: 2021-10-28 22:00:29.498005

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '61507cbdfbb6'
down_revision = '67144dfbc5dd'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('product_order_id_fkey', 'product', type_='foreignkey')
    op.drop_column('product', 'order_id')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('product', sa.Column('order_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.create_foreign_key('product_order_id_fkey', 'product', 'order', ['order_id'], ['id'])
    # ### end Alembic commands ###
