"""missing fields user

Revision ID: 67144dfbc5dd
Revises: 8e38c7d4390e
Create Date: 2021-10-28 02:26:40.461213

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '67144dfbc5dd'
down_revision = '8e38c7d4390e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('is_admin', sa.Boolean(), nullable=True))
    op.add_column('user', sa.Column('password', sa.Text(), nullable=True))
    op.execute('UPDATE "user" SET password = \'jdmb\' WHERE password IS NULL')
    op.execute('ALTER TABLE "user" ALTER COLUMN password SET NOT NULL')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'password')
    op.drop_column('user', 'is_admin')
    # ### end Alembic commands ###
