"""createes relation product-order many-to-many

Revision ID: af7533e14af7
Revises: 61507cbdfbb6
Create Date: 2021-10-28 22:21:03.620079

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'af7533e14af7'
down_revision = '61507cbdfbb6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('orderedProduct',
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('order_id', sa.Integer(), nullable=False),
    sa.Column('product_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['order_id'], ['product.id'], ),
    sa.ForeignKeyConstraint(['product_id'], ['order.id'], ),
    sa.PrimaryKeyConstraint('id', 'order_id', 'product_id')
    )
    op.add_column('product', sa.Column('description', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('product', 'description')
    op.drop_table('orderedProduct')
    # ### end Alembic commands ###
